[package]
name = "tower-otel"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread", "signal"] }
http = "1.2.0"
tower = "0.5.2"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["std", "env-filter", "json", "fmt", "tracing-log"] }
tracing-opentelemetry = "0.28.0"
opentelemetry = { version = "0.27.1", features = ["metrics", "trace"], default-features = false }
opentelemetry_sdk = { version = "0.27.1", features = ["metrics", "rt-tokio", "logs", "trace"], default-features = false }
opentelemetry-semantic-conventions = { version = "0.27.0", default-features = false }
pin-project = "1.1.7"
thiserror = "2.0.7"


tonic = "0.12.2"
http-body = "1.0.1"



