services:
  # Telemetry Components
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.86.0
    # healthcheck:
    #   test: wget --no-verbose --tries=1 --spider http://localhost:13133 || exit 1
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 13133:13133 # health_check extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 4317:4317 # OTLP gRPC receiver

  jaeger:
    image: jaegertracing/all-in-one:1.49
    ports:
      - 16686:16686 # Web UI
      - 14250:14250 # Listen for traces