receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
    timeout: 1s

exporters:
  logging:
    loglevel: info
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, logging]
